# Generated by Django 2.2.4 on 2019-08-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_auto_20190827_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallcomments', to='login.User')),
                ('likes', models.ManyToManyField(related_name='wallcommentlikes', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Wallconvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('privacy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallconvos', to='login.User')),
                ('likes', models.ManyToManyField(related_name='wallconvolikes', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Hubreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallreplies', to='login.User')),
                ('hubcomment_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallreplies', to='dashboard.Hubcomment')),
                ('likes', models.ManyToManyField(related_name='wallreplylikes', to='login.User')),
            ],
        ),
        migrations.AddField(
            model_name='hubcomment',
            name='wallconvo_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallcomments', to='dashboard.Wallconvo'),
        ),
    ]
