# Generated by Django 2.2.4 on 2019-08-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190827_2340'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hubcomment',
            new_name='Wallcomment',
        ),
        migrations.RenameModel(
            old_name='Hubreply',
            new_name='Wallreply',
        ),
    ]
