# Generated by Django 2.2.4 on 2019-08-27 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_auto_20190827_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubconvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubconvos', to='login.User')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubconvolikes', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Hubreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubreplies', to='login.User')),
                ('hubcomment_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubreplies', to='kithub.Hubconvo')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubreplylikes', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Hubcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubcomments', to='login.User')),
                ('hubconvo_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubcomments', to='kithub.Hubconvo')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubcommentlikes', to='login.User')),
            ],
        ),
    ]
