# Generated by Django 2.2.4 on 2019-08-28 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kithub', '0002_auto_20190827_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubcomment',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hubcommentlikes', to='login.User'),
        ),
        migrations.AlterField(
            model_name='hubreply',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hubreplylikes', to='login.User'),
        ),
    ]
