# Generated by Django 2.2.4 on 2019-08-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kithub', '0006_auto_20190828_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubconvo',
            name='like',
            field=models.ManyToManyField(related_name='hubconvolikes', to='login.User'),
        ),
    ]
