# Generated by Django 2.2.4 on 2019-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190827_2340'),
        ('kithub', '0007_auto_20190828_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hubconvo',
            old_name='like',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='hubcomment',
            name='likes',
        ),
        migrations.AddField(
            model_name='hubcomment',
            name='likes',
            field=models.ManyToManyField(related_name='hubcommentlikes', to='login.User'),
        ),
        migrations.RemoveField(
            model_name='hubreply',
            name='likes',
        ),
        migrations.AddField(
            model_name='hubreply',
            name='likes',
            field=models.ManyToManyField(related_name='hubreplylikes', to='login.User'),
        ),
    ]
