# Generated by Django 2.2.4 on 2019-08-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kithub', '0008_auto_20190828_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubcomment',
            name='hubconvo_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubcomments', to='kithub.Hubconvo'),
        ),
        migrations.AlterField(
            model_name='hubreply',
            name='hubcomment_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubreplies', to='kithub.Hubcomment'),
        ),
    ]
