# Generated by Django 2.2.4 on 2019-08-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friends', to='login.User'),
        ),
    ]
