# Generated by Django 2.2.4 on 2019-08-27 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190827_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.date(2019, 8, 27)),
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(null=True, related_name='_user_friend_+', to='login.User'),
        ),
    ]
