# Generated by Django 2.2.4 on 2019-08-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190827_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
